##' Bootstrap GO analysis
##'
##' Performs bootstrap GO analysis.
##' @title Bootstrap GO analysis
##' @param sigGenes Vector coding for differentially expressed genes (value 1) and non-differentially expressed genes (value 0)
##' @param gene2G0 List containing GO-terms per gene
##' @param B Number of bootstrap runs
##' @param tau Percentage (between 0 and 1) of original size of GO-sets to be sampled for bootstrap analysis
##' @param onto Either "BP" for biological process, "MF" for molcular function, or "CC" for celular component
##' @return A list containing the following items:
##' \describe{
##'   \item{nonbootresult}{Table with results of original GO analysis.}
##'   \item{bootresult}{List of size B, where each element is the result of a bootstrap GO analysis.}
##' }
##' @author Shamini Hemandhar Kumar, Klaus Jung
##' @references
##' Alexa, A., & Rahnenführer, J. (2009). Gene set enrichment analysis with topGO. \emph{Bioconductor Improv}, \strong{27}, 1-26. \url{https://mirrors.nju.edu.cn/bioconductor/3.2/bioc/vignettes/topGO/inst/doc/topGO.pdf}
##' @export
##' @examples
##' require(RobustRankAggreg)
##' require(topGO)
##' d <- 10000 ### number of genes
##' sigGenes.example <- rbinom(d, 1, 0.1)
##' names(sigGenes.example) <- paste("gene", 1:d, sep="_")
##' gene2GO.example <- vector(mode="list", length=d)
##' names(gene2GO.example) <- names(sigGenes.example)
##' GOs = paste("GO:000", 1000:9999, sep="")
##' for (j in 1:d) gene2GO.example[[j]] <- sample(GOs, rnbinom(1, 1, 0.1),replace=FALSE)
##' 
##' resultGO = boot.GO(sigGenes=sigGenes.example, gene2GO=gene2GO.example)
##' resultAggr = aggr.boot.GO(resbootGO=resultGO)
##' head(resultAggr)
##' compareRank(aggrbootGO=resultAggr, lim=100, ord="original", ident=FALSE)
boot.GO <- function(sigGenes, gene2GO, B=2, tau=0.95, onto="BP") {
	
	print("Step1: non-bootstrap analysis")
	GOdata0 <- new("topGOdata",
		ontology = onto,
		allGenes = sigGenes,
		geneSelectionFun = function(x)(x == 1),
		annot = annFUN.gene2GO, gene2GO=gene2GO)
	results.fisher0 <- runTest(GOdata0, algorithm="classic", statistic="fisher")
	goEnrichment0 <- GenTable(GOdata0, Fis=results.fisher0, orderBy="fisher", topNodes=length(results.fisher0@score), numChar=1000)
	
	boot.results_GO <- vector(mode="list", length=B)
	names(boot.results_GO) = paste("Bootstrap run", 1:B, sep="")
	for (b in 1:B) {
		print(paste("Bootstrap run:", b))
		go_boot <- sample(sigGenes, tau*d, replace=FALSE)
		GOdata <- new("topGOdata",
			ontology = onto,
			allGenes = go_boot,
			geneSelectionFun = function(x)(x == 1),
			annot = annFUN.gene2GO, gene2GO=gene2GO)
		results.fisher <- runTest(GOdata, algorithm="classic", statistic="fisher")
		goEnrichment <- GenTable(GOdata, Fis=results.fisher, orderBy="fisher", topNodes=length(results.fisher@score), numChar=1000)
		boot.results_GO[[b]] <- goEnrichment
	}
	return(list(nonbootresult=goEnrichment0, bootresult=boot.results_GO))
}

##' Aggregation of bootstrap GO analyses
##'
##' Aggregates ranks from B bootstrap GO analyses
##' @title Aggregate boostrap GO analysis
##' @param resbootGO A list as generated by the function boot.GO
##' @return A matrix containing the following columns: GO IDs, rank aggregation score, ranks from the non-bootstrap GO analysis, B colums with ranks from the bootstrap analyses
##' @author Shamini Hemandhar Kumar, Klaus Jung
##' @references
##'	Kolde, R., Laur, S., Adler, P., & Vilo, J. (2012). Robust rank aggregation for gene list integration and meta-analysis. \emph{Bioinformatics}, \strong{28(4)}, 573-580. \url{https://doi.org/10.1093/bioinformatics/btr709}
##' @export
##' @examples
##' require(RobustRankAggreg)
##' require(topGO)
##' d <- 10000 ### number of genes
##' sigGenes.example <- rbinom(d, 1, 0.1)
##' names(sigGenes.example) <- paste("gene", 1:d, sep="_")
##' gene2GO.example <- vector(mode="list", length=d)
##' names(gene2GO.example) <- names(sigGenes.example)
##' GOs = paste("GO:000", 1000:9999, sep="")
##' for (j in 1:d) gene2GO.example[[j]] <- sample(GOs, rnbinom(1, 1, 0.1),replace=FALSE)
##' 
##' resultGO = boot.GO(sigGenes=sigGenes.example, gene2GO=gene2GO.example)
##' resultAggr = aggr.boot.GO(resbootGO=resultGO)
##' head(resultAggr)
##' compareRank(aggrbootGO=resultAggr, lim=100, ord="original", ident=FALSE)
aggr.boot.GO <- function(resbootGO) {
	B <- length(resbootGO[[2]])
	rankedGO <- vector(mode="list", length=B)
	for (b in 1:B) rankedGO[[b]] <- resbootGO[[2]][[b]]$GO.ID
	rankScore <- aggregateRanks(glist=rankedGO)
	rownames(rankScore) <- NULL
	
	rankScore[,3] <- match(rankScore$Name, resbootGO[[1]]$GO.ID)
	names(rankScore)[3] <- "rankRun_nonBoot"
	
	for (b in 1:B) {
		rankScore[,3+b] <- match(rankScore$Name, rankedGO[[b]])
		names(rankScore)[3+b] <- paste("rankRun", b, sep="_")
	}
	return(rankScore)
}

##' Visualisation of bootstrap GO analyses
##'
##' Generates a plot for visualisation of bootstrap GO analyses
##' @title Visualisation of bootstrap GO analyses
##' @param aggrbootGO A table as returned by the function aggr.boot.GO
##' @param lim Number of top ranked GO terms to be displayed in the plot
##' @param ord Character with value "original" for ranking GO terms according to non-bootstrap GO analysis
##' @param ident Boolean value. If true, the user is enabled to click and annotate GO terms in the plot
##' @return No return value
##' @author Shamini Hemandhar Kumar, Klaus Jung
##' @references
##' Alexa, A., & Rahnenführer, J. (2009). Gene set enrichment analysis with topGO. \emph{Bioconductor Improv}, \strong{27}, 1-26. \url{https://mirrors.nju.edu.cn/bioconductor/3.2/bioc/vignettes/topGO/inst/doc/topGO.pdf}
##'	Kolde, R., Laur, S., Adler, P., & Vilo, J. (2012). Robust rank aggregation for gene list integration and meta-analysis. \emph{Bioinformatics}, \strong{28(4)}, 573-580. \url{https://doi.org/10.1093/bioinformatics/btr709}
##' @export
##' @examples
##' require(RobustRankAggreg)
##' require(topGO)
##' d <- 10000 ### number of genes
##' sigGenes.example <- rbinom(d, 1, 0.1)
##' names(sigGenes.example) <- paste("gene", 1:d, sep="_")
##' gene2GO.example <- vector(mode="list", length=d)
##' names(gene2GO.example) <- names(sigGenes.example)
##' GOs = paste("GO:000", 1000:9999, sep="")
##' for (j in 1:d) gene2GO.example[[j]] <- sample(GOs, rnbinom(1, 1, 0.1),replace=FALSE)
##' 
##' resultGO = boot.GO(sigGenes=sigGenes.example, gene2GO=gene2GO.example)
##' resultAggr = aggr.boot.GO(resbootGO=resultGO)
##' head(resultAggr)
##' compareRank(aggrbootGO=resultAggr, lim=100, ord="original", ident=FALSE)
compareRank <- function(aggrbootGO, lim=100, ord="original", ident=FALSE) {
	
	if (ord=="original") {
		o <- order(aggrbootGO$rankRun_nonBoot)
		aggrbootGO <- aggrbootGO[o,]
	}
	
	N <- nrow(aggrbootGO)
	x0 <- aggrbootGO$rankRun_nonBoot
	y0 <- rank(aggrbootGO$Score)
	x <- x0[1:lim]
	y = y0[1:lim]
	colo = rep(1, lim)
	colo[which(x<y)] = 2
	colo[which(x>y)] = 3
	plot(x, y, cex.lab=1.5, cex.axis=1.5, xlab="Rank of non-bootstrap analysis", ylab="Rank of bootstrap score", col=colo)
	abline(0, 1, col=4, lwd=2)
	points(x, y, col=colo, lwd=2)
	legend("topleft", c("loss", "same", "gain"), col=c(2, 1, 3), pch=15, cex=1.5)
	if (ident==TRUE) identify(x, y, labels=aggrbootGO$Name[1:lim])
}